import React from "react";

export const metadata = {
  title: "about maxiApp",
  description: "Generated by maxi",
  keywords: "tienda, online, ecommerce",
};

const Aboutpage = () => {
  return <h1>ABOUUUUUUUT</h1>;
};

export default Aboutpage;
