import Link from "next/link";

export const metadata = {
  title: "maxiApp - tienda oficial",
  description: "Generated by maxi",
  keywords: "tienda, online, ecommerce",
};

const layout = ({ children }) => {
  return (
    <>
      <h3>Seccion tienda</h3>
      <ul>
        <li>
          <Link href="/tienda/categorias">Categorias</Link>
        </li>
        <li>
          <Link href="/tienda/categorias/computadoras">Computadoras</Link>
        </li>
      </ul>
      {children}
    </>
  );
};

export default layout;
